version: 2


shared:
  jobs: &jobs
    - build-firefox-60.6.3esr:
        context: Docker Hub Upload
    - build-firefox-66.0.5:
        context: Docker Hub Upload
    - build-chromium-latest:
        context: Docker Hub Upload

  build: &build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build base Docker image
          command: |
            cd base &&
            docker build \
              --no-cache \
              -t saltyrtc/circleci-image-js-base:build \
              .
      - run:
          name: Build ${BROWSER} Docker image
          command: |
            cd $BROWSER &&
            docker build \
              --no-cache \
              --build-arg BROWSER_VERSION=$BROWSER_VERSION \
              -t saltyrtc/circleci-image-js:${BROWSER}-${BROWSER_VERSION} \
              .
      - deploy:
          name: Push Docker image
          command: |
            if [[ "${CIRCLE_BRANCH}" = "master" ]]; then
              docker login -u $DOCKER_LOGIN -p $DOCKER_ACCESS_TOKEN && \
              docker push saltyrtc/circleci-image-js:${BROWSER}-${BROWSER_VERSION}
            fi


jobs:
  build-firefox-60.6.3esr:
    <<: *build
    docker:
      - image: docker:stable
    environment:
      - BROWSER: firefox
      - BROWSER_VERSION: 60.6.3esr

  build-firefox-66.0.5:
    <<: *build
    docker:
      - image: docker:stable
    environment:
      - BROWSER: firefox
      - BROWSER_VERSION: 66.0.5

  build-chromium-latest:
    <<: *build
    docker:
      - image: docker:stable
    environment:
      - BROWSER: chromium
      - BROWSER_VERSION: latest


workflows:
  version: 2

  # Build on push
  on_push:
    jobs: *jobs

  # Build every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs: *jobs
