version: 2

references:
  build-jobs: &build-jobs
    - build-firefox-50.1.0
    - build-firefox-52.6.0esr
    - build-firefox-58.0.2
    - build-chromium-latest
  build-steps: &build-steps
      - checkout
      - setup_remote_docker
      - run:
          name: Build base Docker image
          command: |
            cd base &&
            docker build \
              --no-cache \
              -t saltyrtc/circleci-image-js-base:build \
              .
      - run:
          name: Build ${BROWSER} Docker image
          command: |
            cd $BROWSER &&
            docker build \
              --no-cache \
              -t saltyrtc/circleci-image-js:${BROWSER}-${BROWSER_VERSION} \
              .
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_API_KEY && \
            docker push saltyrtc/circleci-image-js:${BROWSER}-${BROWSER_VERSION}

jobs:
  build-firefox-50.1.0:
    docker:
      - image: docker:stable
    steps: *build-steps
    environment:
      - BROWSER: firefox
      - BROWSER_VERSION: 50.1.0
  build-firefox-52.6.0esr:
    docker:
      - image: docker:stable
    steps: *build-steps
    environment:
      - BROWSER: firefox
      - BROWSER_VERSION: 52.6.0esr
  build-firefox-58.0.2:
    docker:
      - image: docker:stable
    steps: *build-steps
    environment:
      - BROWSER: firefox
      - BROWSER_VERSION: 58.0.2
  build-chromium-latest:
    docker:
      - image: docker:stable
    steps: *build-steps
    environment:
      - BROWSER: chromium
      - BROWSER_VERSION: latest

workflows:
  version: 2

  # Build on push
  on_push:
    jobs: *build-jobs

  # Build every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs: *build-jobs
