#!/bin/bash
saltyrtc-server \
    -v 6 \
    serve \
    -tc /saltyrtc/certs/localhost.cert.pem \
    -tk /saltyrtc/certs/localhost.key.pem \
    -p 8765 \
    -k $SALTYRTC_SERVER_PERMANENT_KEY > /saltyrtc/serverlog.txt 2>&1 &
echo $!
